### DISCUSSION TITLE
Activity does not show playing status

### DISCUSSION THREAD

**Discussion by githuber110** [FunkeyFlo/ps5-mqtt#272] [General]
Hi all,

I just found that great add-on and set it up based on the documentation. 

But for some reason I just get the "idle" activity status instead of seeing "playing". Other attributes like the games name are even not in the list of available attributes.

I can see if the ps5 is awake and I can also turn if off and on using the power entity.

Here is my config:

```
mqtt:
  host: 192.168.178.200
  port: "1883"
  user: homeassistant
  pass: "!secret mqtt_secret"
logger: "@ha:ps5:*"
device_check_interval: 5000
device_discovery_interval: 60000
account_check_interval: 5000
include_ps4_devices: false
psn_accounts:
  - username: <any random name label>
    npsso: "!secret npsso_secret"
    preferred_ps5: <my PS5 device ID from the web gui>
```

Any ideas what I'm missing and which configuration I should take a closer look?
