### DISCUSSION TITLE
PS5 MQTT Configuration error

### DISCUSSION THREAD

**Discussion by ContraVern** [FunkeyFlo/ps5-mqtt#298] [Q&A]
The documentation says that the psn_accounts field is optional, but I am getting this error when I leave it blank.

Failed to save add-on configuration, Missing option 'psn_accounts' in root in PS5 MQTT (df2164f9_ps5_mqtt). Got {'mqtt': {}, 'logger': '@ha:ps5:*', 'device_check_interval': 5000, 'device_discovery_interval': 60000, 'account_check_interval': 5000, 'include_ps4_devices': False}

I do not see the npsso field, but I am not sure if that is the issue. Below is a screen shot of my attempted configuration. Any help or support would be greatly appreciated! (coffee)

![image](https://github.com/FunkeyFlo/ps5-mqtt/assets/19216953/83a16759-eba0-4a15-b957-3647ed4846ac)

**Comment by FunkeyFlo** [comment]
This is probably because you "touched" the npsso field, for example when you cleared it using the UI.

The HA add-on config editor has some issues with complex/list type values.

If you open the config in the `yaml` editor you'll probably see something like:
```yaml
...
psn_accounts: {}
...
```

However, this should have been:
```yaml
...
psn_accounts: []
...
```

**Comment by SuperNestendo** [comment]
Hello @FunkeyFlo . I came here with the same issue and am a bit lost as to how to fix it. The install did have the square brackets after psn_accounts but I can't figure out how to enter the data. I've tried the following in yaml:
```
psn_accounts: []
  username: SuperNes10do
  npsso: '!secret mynpsso'
  preferred_ps5: #intentionally left blank
  preferred_ps4: #intentionally left blank
```

```
psn_accounts: [
  username: SuperNes10do
  npsso: '!secret mynpsso'
  preferred_ps5: #intentionally left blank
  preferred_ps4: #intentionally left blank
]
```

Neither work. I have also omitted preferred attributes but it will not save. The save button is greyed out and when I click it it states I have to restart the service and clears the input I have added. Sorry if this is a noob question but I am at a loss.

**Reply by FunkeyFlo** [reply]
You're missing some syntax. As mentioned before you have to match all the syntax from the examples **precisely**.

You can either do (this is the *exact* example from the docs):
```yaml
psn_accounts:
  - username: MyPsnUser            
    npsso: '!secret my_npsso'
    preferred_ps5: 70C881D600B0
    preferred_ps4: 60E899D600B0
```

Or:
```yaml
psn_accounts: [
  {
    username: MyPsnUser,            
    npsso: '!secret my_npsso',
    preferred_ps5: 70C881D600B0,
    preferred_ps4: 60E899D600B0
  }
]
```

Either way; these are both valid examples of lists with complex values in yaml. Both your examples, needless to say, were not. For anyone getting confused by this. Pleaaaase refer to documentation on y'all syntax, I've had this question a million times now and the docs contain the correct examples. Somehow this is still a huge hurdle for people and I cannot make this easier.
HA really need to improve the graphical editor for add-on config as the list/complex value editors just being yaml windows is just horrid.
