### DISCUSSION TITLE
NPSSO only works without !Secret option for NPSSO

### DISCUSSION THREAD

**Discussion by thepilzkopf** [FunkeyFlo/ps5-mqtt#481] [General]
Hi, 

thank you for your work. 
I got everything to work with just a small problem. 

When I enter the NPSSO, it only takes it if I type it in without !secret
When I enter it using your template with !secret I get the message:

"Failure on saving the Addon-Configuration, Unknown secret
If I delete the phrase !secret everything works totally fine

My YAML
```
mqtt: {}
logger: "@ha:ps5:*"
device_check_interval: 5000
device_discovery_interval: 60000
account_check_interval: 5000
include_ps4_devices: false
psn_accounts:
  - username: xxxx
    npsso: '!secret npsso'
    preferred_ps5: xxxxx
device_discovery_broadcast_address: 192.168.5.12`
```

Do you have an idea what I did wrong?
Thanks!
