### DISCUSSION TITLE
Activeapp_title and Activeapp_Image Not Working

### DISCUSSION THREAD

**Discussion by dmcnaugh15** [FunkeyFlo/ps5-mqtt#538] [Q&A]
**THE ISSUE / PROBLEM / OBSERVATIONS:**
Activeapp_title and activeapp_Image entities are no longer detected / available via MQTT broker.  On my initial setup a few months ago, they were working.  I was never able to get nvm working to create refresh tokens.  So, my plan was to just manually refresh the npsso token every couple months by logging in and copying it over to the configuration section.  This is the first time I've tried manually refreshing the npsso.

**WHAT I'VE TRIED**
Uninstalled ps5-mqtt addon 
Deleted all the mqtt instances from MQTT explorer
Deleted any residual mqtt entities from home assistant
Restarted HA
Reinstalled / reconfigured ps5-mqtt addon

**LOGS (Potentially relevant line):**
_@ha:ps5:error Error: Registration error: 403: Forbidden: Remote is already in use_

**CONFIGURATION (YAML):**
```
mqtt:
  host: 192.168.1.83
  port: "1883"
  user: mqtt-user
  pass: xxxxxx
logger: "@ha:ps5:*"
device_check_interval: 5000
device_discovery_interval: 60000
account_check_interval: 5000
include_ps4_devices: false
psn_accounts:
  - username: dmcnaugh
    npsso: xxxxx
    preferred_ps5: xxxxxx
```

Any ideas or suggestions would be greatly appreciated!
