### ISSUE TITLE
Status of Activity entity sporadically changes to idle for some seconds

### ISSUE THREAD

**Issue by tr4nt0r** [FunkeyFlo/ps5-mqtt#297]
### Description of the issue

When playing the Status of the Activity Entity sporadically changes to idle for about 5s and then changes back to the previous state.
In the logs i see the error message 
`psn-api Unable to retrieve PSN information. API response: "401:Unauthorized`
at the exact same time and the time it changes to idle also matches the account check interval.

I think this is related to issue #157 and though it maybe cannot be fixed, maybe the behaviour could be changed. I have an automation that is triggered when I start playing a certain game but i don't want it to be triggered at random while playing. 

I would suggest that the Status of the entity is not updated immediately after a login error but maybe after retrying to authenticate several times. And if the Status still cannot be retrieved maybe the status of the activity entity should not be set to idle but to unavailable instead.

### Addon version

1.3.1 

### Platform

Home Assistant 2023.8.3
Supervisor 2023.08.1
Operating System 10.5
Frontend 20230802.1 - latest

**Comment by tr4nt0r** [comment]
Just a small follow-up, I found a workaround for this issue . I added a second trigger to my automation that whould block the execution for the time of 2 account check intervals. So if the sensor goes from playing to idle because the account check fails but succeeds in the next interval, it will not trigger the automation. 


```

alias: "FFXIV Einmalpasswort"
description: >-
  Bei starten von Final Fantasy XIV auf dem Fernseher ein Einmalpasswort
  anzeigen
trigger:
  - platform: state
    entity_id:
      - sensor.ps5_***_activity
    for:
      hours: 0
      minutes: 0
      seconds: 0
    id: to_playing
    attribute: activity
    to: playing
  - platform: state
    entity_id:
      - sensor.ps5_***_activity
    attribute: activity
    from: playing
    to: idle
    id: playing_to_idle
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - to_playing
          - condition: state
            entity_id: sensor.ps5_***_activity
            attribute: title_id
            state: PPSA02955_00
          - condition: device
            device_id: ***********************************
            domain: media_player
            entity_id: media_player.sony_kd_55xg8577
            type: is_on
            enabled: true
          - condition: or
            conditions:
              - condition: state
                entity_id: media_player.sony_kd_55xg8577
                attribute: source
                state: PlayStation 5
              - condition: state
                entity_id: media_player.sony_kd_55xg8577
                attribute: source
                state: HDMI 1
        sequence:
          - service: script.ffxiv_otp
            data: {}
      - conditions:
          - condition: trigger
            id:
              - playing_to_idle
          - condition: template
            value_template: "{{trigger.from_state.attributes.title_id == 'PPSA02955_00'}}"
        sequence:
          - delay:
              hours: 0
              minutes: 0
              seconds: 8
              milliseconds: 0
mode: single
max_exceeded: silent

```

Would just be a lot easier if the status would go to unavailable or unknown instead of idle.
