### ISSUE TITLE
No devices discovered on a fresh install

### ISSUE THREAD

**Issue by mazay** [FunkeyFlo/ps5-mqtt#352]
### Description of the issue

Fresh install of the add-on. I have configured the `mqtt` section and `device_discovery_broadcast_address` since I have multiple VLANs:
```yaml
mqtt:
  host: 172.16.111.204
  port: "9200"
  user: REDACTED
  pass: REDACTED
logger: "@ha:ps5:*"
device_check_interval: 5000
device_discovery_interval: 60000
account_check_interval: 5000
include_ps4_devices: true
psn_accounts: []
device_discovery_broadcast_address: 10.113.118.20
```

I can discover devices (at least one of them) using the `playactor browse` CLI:
```
> playactor browse
{
  "address": {
    "address": "10.113.118.66",
    "family": "IPv4",
    "port": 9302,
    "size": 170
  },
  "hostRequestPort": 997,
  "extras": {
    "statusLine": "620 Server Standby",
    "statusCode": "620",
    "statusMessage": "Server",
    "status": "STANDBY"
  },
  "discoveryVersion": "00030010",
  "systemVersion": "08400005",
  "id": "F4641262DC56",
  "name": "PS5-430",
  "status": "STANDBY",
  "type": "PS5"
}
```

Please advise what can be done to make it work.

### Addon version

1.3.1

### Platform

Core: 2023.12.3
Supervisor: 2023.11.6
Operating System: 11.2
Frontend: 20231208.2

### Logs of the issue (if applicable)

logs are rather useless:
```
Starting PS5-MQTT...
2023-12-18T13:14:32.806Z @ha:ps5:webserver Server listening on PORT: 62806
```
