### ISSUE TITLE
Template sensor not working as expected

### ISSUE THREAD

**Issue by Martijnvanoijen** [FunkeyFlo/ps5-mqtt#414]
### Description of the issue

I made a template sensor for my dashboard to show the title that is being played on an image card.

so i made the following two sensors:

#### PS5 afbeelding
```yaml
name: “ps5 game afb”
unique_id: ps5-a1
state: “{{ state_attr(‘sensor.ps5_maytijn_activity’,‘title_image’) }}”
```
#### PS5 titel
```yaml
name: “ps5 game titel”
unique_id: ps5-a2
state: “{{ state_attr(‘sensor.ps5_maytijn_activity’,‘title_name’) }}”
```
Both working as expected in the test area.

But when i look at the sensor for the title name, i will see that the title “was” correct, but from the moment i am looking at the sensor it shows “unknown”.

It seems to changes to unknown (onbekend) when i look at it, but the dashboard card is also not able to show the title of the game.

the sensor for the image works as expected. Any clue to how to fix this?

### Addon version

1.3.3

### Platform

Core 2024.06, supervisor 2024.06, OS 12.3

### Logs of the issue (if applicable)

Nothing to see in the log.
