### ISSUE TITLE
docker env "PSN_ACCOUNTS" mandatory

### ISSUE THREAD

**Issue by matt8707** [FunkeyFlo/ps5-mqtt#46]
### Description of the issue

Hello, upgrading from 0.7.1 to 1.0.1 (HA Core) yields an error. 

After adding ENV `PSN_ACCOUNTS` everything works as expected :+1: 

```yaml
  ps5-mqtt:
    container_name: ps5-mqtt
    image: ghcr.io/funkeyflo/ps5-mqtt/amd64
    volumes:
      - /volume1/docker/ps5-mqtt:/config
    network_mode: host
    entrypoint: /config/run.sh
    environment:
      - MQTT_HOST=${MQTT_HOST}
      - DEVICE_CHECK_INTERVAL=5000
      - DEVICE_DISCOVERY_INTERVAL=60000
      - INCLUDE_PS4_DEVICES=false
      - FRONTEND_PORT=8645
      - CREDENTIAL_STORAGE_PATH=/config/credentials.json
      - 'PSN_ACCOUNTS=[{"username": "PSN", "npsso":"${NPSSO}"}]' # <- mandatory
      - ACCOUNT_CHECK_INTERVAL=5000
      - DEBUG=@ha:ps5:*
    restart: always
```

### Addon version

1.0.1

### Platform

Home Assistant 2022.8.6
Frontend-version: 20220802.0 - latest

### Logs of the issue (if applicable)

```js
SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (/app/server/dist/index.js:81:25)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
Starting PS5-MQTT...
undefined:1
undefined
^
```
