### ISSUE TITLE
Start-up error when using more than one PSN account 

### ISSUE THREAD

**Issue by jannislehmann** [FunkeyFlo/ps5-mqtt#68]
### Description of the issue

When adding more than one PSN account to the configuration, the add-on fails to start.
The configuration looks like the following:
```yaml
- username: First
  npsso: "!secret first"
- username: Second
  npsso: "!secret second"
```

Another user also reported the [same issue](https://community.home-assistant.io/t/ps5-mqtt-control-playstation-5-devices-using-mqtt/441141/36?u=cludch).

### Addon version

1.0.1

### Platform

Home Assistant 2022.9.1
Supervisor 2022.08.6
Operating System 8.5
Frontend 20220907.0 - latest

### Logs of the issue (if applicable)

`/app/run.sh: line 26: [: {"username":"User1","npsso":"secret"}: binary operator expected`
